### ISSUE TITLE
Lurking Horror

### ISSUE THREAD

**Issue by MarcoVerpelli** [a2-4am/pitch-dark#1]
Lurking Horror version 221/870912 and 219/870918 when you quit they stops with the message "Internal error 01."

If you save in any slot then resume the game you get "Internal error 01." message and it quit

Marco

P.S.

I forgot, the game is still copy protected, you need to know the login / password = 872325412 / UHLERSOTH to continue.

**Comment by peterferrie** [comment]
Internal error is fixed in b9d4d373bb45827f71be5864a7524291ff8dbf12.
I wasn't aware of the copy-protection.  I will patch it separately.

**Comment by peterferrie** [comment]
Fixed in f92cf65c79bb750015109caca4b52c7b34e4586d

**Comment by peterferrie** [comment]
Thanks for the report.
