### ISSUE TITLE
zork ii hints error

### ISSUE THREAD

**Issue by mtklr** [a2-4am/pitch-dark#13]
I was just recently poking around with Pitch Darker though... I get this trying to access Hints for Zork II (tried with different versions of Pitch Darker and different emulators):

```
No .sav file, saving disabledInternal error 15.
On Beyond Z-Machine revision 2/191025
```

My (novice-level) pass through the code didn't lead me to anything...

Thanks.:)

**Comment by peterferrie** [comment]
fixed in 3ec8019ac69619b9d0a592e4eaffb34aefbad136
