### ISSUE TITLE
Add option to see a list of titles instead of having to page through them one by one

### ISSUE THREAD

**Issue by a2sheppy** [a2-4am/pitch-dark#3]
The UI for Pitch Dark is awesome... but sometimes you don't want to have to flip through the list one by one. Instead, it would help to have a simple scrolling list of titles to go through, to quickly navigate to the screen for a given title.

**Comment by chris-torrence** [comment]
I'm currently working on this. See https://github.com/chris-torrence/pitch-dark/tree/catalog

![cat1](https://user-images.githubusercontent.com/5461379/44247484-dc24b580-a1a1-11e8-949d-0f580284ee3e.png)

![cat2](https://user-images.githubusercontent.com/5461379/44247492-e3e45a00-a1a1-11e8-85c2-73eb615f2362.png)

**Comment by chris-torrence** [comment]
I just did a pull request for this feature. Here's what the screen looks like:
![pd](https://user-images.githubusercontent.com/5461379/44624251-272b8080-a8a6-11e8-94a7-f810702149ad.jpg)
