### ISSUE TITLE
Add keys to speed up navigating games

### ISSUE THREAD

**Issue by a2sheppy** [a2-4am/pitch-dark#7]
Let the "1" and "9" (or "1" through "9") keys scroll to the first and last (or proportionally throughout) the game list.

Consider allowing letter keys to jump to the first title with that as its first letter, changing the shortcuts for the existing buttons to use other characters, or control keys (or use control keys for jumping to titles by letter, but the other way works better).

**Comment by chris-torrence** [comment]
This could be addressed with the Catalog screen for issue #3

**Comment by a2-4am** [comment]
fixed in https://github.com/a2-4am/pitch-dark/commit/3bd842387b93a99ae304a76d956dbe42032bbc34
